using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.SceneManagement;

public class WhiteLife : MonoBehaviour
{
    bool isDead = false;
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        if (isDead == true)
        {
            SceneManager.LoadScene("Level1");
        }
    }
    
    void OnCollisionEnter2D(Collision2D col)
    {
        if (col.gameObject.tag != "Blanco" && col.gameObject.tag != "Player" && col.gameObject.tag != "Wall")
        {
            isDead = true;
        }
    }
    
}
